### ISSUE TITLE
What does test-time refinement mean?

### ISSUE THREAD

**Issue by Rodger-Huang** [ifnspaml/SGDepth#5]
Hi, in your paper, you said the results were not compared to methods with test-time refinement. 
What do you mean by test-time refinement?

**Comment by klingner** [comment]
Hi, test-time refinement essentially means that the network weights are updated and fine-tuned based on each single test-sample. Thereby the network is optimized at test-time to each single test sample. As this step is applied during testing on top of the pre-trained network, it would be possible to improve each of the methods reported in the paper further, which is why a comparison between methods is only meaningfull if and only if all methods either use or don't use test-time refinement. An example of such a method can be found in https://arxiv.org/pdf/1811.06152.pdf.

**Comment by Rodger-Huang** [comment]
Now I get it. Thank you for your explanation!
